# Generated by Django 4.0.4 on 2022-04-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
