version: "3.10.1"

services:
  db:
    image: postgres
    volumes:
      - ./db_django:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nft_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/nft_app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=nft_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db