# Generated by Django 4.0.4 on 2022-04-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_drf', '0002_alter_token_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='media_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='token',
            name='owner',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='token',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='token',
            name='unique_hash',
            field=models.CharField(default='ee244497594f148c1705', max_length=20, unique=True),
        ),
    ]
