# Generated by Django 4.0.4 on 2022-04-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_drf', '0003_alter_token_media_url_alter_token_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='media_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='token',
            name='owner',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='token',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='token',
            name='unique_hash',
            field=models.CharField(default='57c515060a2e35b1df5a', max_length=500, unique=True),
        ),
    ]
